name: Artifact CI

on:
  push:
    branches:
      - '**'

permissions:
  contents: write

jobs:
  publish:
    name: Publish To Maven
    runs-on: macos-latest
    env:
      JFROG_USER: ${{ secrets.JFROG_USER }}
      JFROG_PASSWORD: ${{ secrets.JFROG_PASSWORD }}
      SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
      SIGNING_PASSWORD: ${{ secrets.GPG_SIGNING_PASSWORD }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 22
      - name: Build plugin
        uses: gradle/actions/setup-gradle@v3
      - run: ./gradlew linkReleasexEcutableMingwX64 linkReleaseExecutableMacosArm64 linkReleaseExecutableMacosX64
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: build.${{ github.run_number }}
          files: |
            build/**/*.exe         
            build/**/*.kexe         
