name: Artifact CI

on:
  push:
    branches:
      - '**'

jobs:
  publish:
    name: Publish To Maven
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 19
      - name: Build plugin
        uses: gradle/gradle-build-action@v2
        env:
          JFROG_USER: ${{ secrets.JFROG_USER }}
          JFROG_PASSWORD: ${{ secrets.JFROG_PASSWORD }}
          SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.GPG_SIGNING_PASSWORD }}
        with:
          arguments: linkDebugExecutableMingwX64 linkDebugExecutableMacosArm64 linkDebugExecutableMacosX64
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: build.${{ github.run_number }}
          files: |
            build/**/*.exe         
            build/**/*.kexe         
